import { Injectable, Logger } from "@nestjs/common";
import { PrismaService } from "../../prisma/prisma.service";
import { AnalyticsService } from "../../analytics/analytics.service";
import { HarvestingService } from "../../tax/harvesting.service";
import { GoalsService, type GoalSuccessProbability, type GoalSuccessProbabilityError } from "../../goals/goals.service";
import { LlmOrchestratorService } from "../llm/llm-orchestrator.service";
import type { AiSuggestionType } from "@prisma/client";

function isSuccessProbabilityError(x: GoalSuccessProbability | GoalSuccessProbabilityError): x is GoalSuccessProbabilityError {
  return "error" in x;
}

const REBALANCE_CONCENTRATION_THRESHOLD_PCT = 40;
const SELL_SINGLE_HOLDING_THRESHOLD_PCT = 25;
const LOW_SUCCESS_PROBABILITY_THRESHOLD = 0.5;
const MIN_HARVEST_LOSS_TO_SUGGEST = 50; // ignore trivial losses

interface DraftSuggestion {
  type: AiSuggestionType;
  title: string;
  description: string;
  dataPoint: Record<string, unknown>;
  dedupeKey: string;
}

/**
 * Every suggestion here is triggered by a real threshold check against real
 * Phase 11 (allocation)/Phase 13 (goal probability)/Phase 15 (harvesting)
 * data — never an LLM "deciding" something is worth suggesting. The LLM
 * (when configured/reachable) is only asked to rewrite `description` in
 * more natural language; on failure it falls back to the rules-generated
 * template description, so a suggestion is never blocked by an LLM outage.
 * BUY suggestions are NOT generated by this phase — see STATUS.md: no rule
 * this pass built was defensible enough to recommend a specific purchase,
 * so that suggestion type is a documented gap, not a fabricated rule.
 */
@Injectable()
export class SuggestionEngineService {
  private readonly logger = new Logger(SuggestionEngineService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly analytics: AnalyticsService,
    private readonly harvesting: HarvestingService,
    private readonly goals: GoalsService,
    private readonly orchestrator: LlmOrchestratorService,
  ) {}

  async generateForUser(userId: string): Promise<{ created: number; total: number }> {
    const drafts: DraftSuggestion[] = [];

    drafts.push(...(await this.checkHarvesting(userId)));
    drafts.push(...(await this.checkConcentration(userId)));
    drafts.push(...(await this.checkGoalProbability(userId)));

    let created = 0;
    for (const draft of drafts) {
      const description = await this.refineDescription(draft);
      try {
        await this.prisma.aiSuggestion.create({
          data: { userId, type: draft.type, title: draft.title, description, dataPoint: draft.dataPoint as never, dedupeKey: draft.dedupeKey },
        });
        created++;
      } catch (err) {
        // Unique constraint on (userId, dedupeKey) — same pattern as Phase
        // 17's Notification idempotency guard. A conflict just means this
        // exact condition already has an active card; not an error.
        if (!isUniqueConstraintViolation(err)) throw err;
      }
    }
    return { created, total: drafts.length };
  }

  private async checkHarvesting(userId: string): Promise<DraftSuggestion[]> {
    const candidates = await this.harvesting.getHarvestCandidates(userId, "US").catch(() => []);
    return candidates
      .filter((c) => Math.abs(c.unrealizedLoss) >= MIN_HARVEST_LOSS_TO_SUGGEST)
      .map((c) => ({
        type: "TAX_HARVEST" as const,
        title: `Consider harvesting the loss on ${c.lot.displayName}`,
        description: `${c.lot.displayName} is currently worth ${c.currentValue.toFixed(2)} against a cost basis of ${c.costBasisTotal.toFixed(2)} — an unrealized loss of ${Math.abs(c.unrealizedLoss).toFixed(2)} (${c.unrealizedLossPct.toFixed(1)}%). Realizing it could offset up to ${c.offsettableRealizedGain.toFixed(2)} in gains elsewhere, an estimated tax saving of ${c.estimatedTaxSaving.toFixed(2)}.`,
        dataPoint: {
          lotId: c.lot.id,
          ticker: c.lot.ticker,
          currentValue: c.currentValue,
          costBasisTotal: c.costBasisTotal,
          unrealizedLoss: c.unrealizedLoss,
          unrealizedLossPct: c.unrealizedLossPct,
          estimatedTaxSaving: c.estimatedTaxSaving,
        },
        dedupeKey: `tax-harvest:${c.lot.id}`,
      }));
  }

  private async checkConcentration(userId: string): Promise<DraftSuggestion[]> {
    // Real shape from apps/quant/analytics/allocation.py's breakdown_by_dimension:
    // byDimension.assetClass.groups[] = { label, value, weight (0-1 fraction, not a percentage) }.
    //
    // BUG FIX (found live, 2026-09-07): getAllocation calls the Python quant
    // microservice (apps/quant, port 8000) -- when it's unreachable, this
    // threw uncaught, which killed the ENTIRE generateForUser() call
    // (including checkHarvesting's and checkGoalProbability's already-
    // computed results, since nothing here or in generateForUser caught
    // it), silently producing zero suggestions with no visible error.
    // checkHarvesting and checkGoalProbability already degrade gracefully
    // via .catch() -- this brings checkConcentration in line with that same
    // established resilience pattern instead of being the one exception.
    const allocation = (await this.analytics.getAllocation(userId).catch((err) => {
      this.logger.warn(`getAllocation failed, skipping concentration checks: ${String(err)}`);
      return null;
    })) as {
      byDimension?: { assetClass?: { groups: Array<{ label: string; value: number; weight: number }> } };
      totalValue?: number;
    } | null;
    const groups = allocation?.byDimension?.assetClass?.groups ?? [];
    const out: DraftSuggestion[] = [];

    for (const bucket of groups) {
      const percentage = bucket.weight * 100;
      if (percentage >= REBALANCE_CONCENTRATION_THRESHOLD_PCT) {
        out.push({
          type: "REBALANCE",
          title: `${bucket.label} is ${percentage.toFixed(0)}% of your portfolio`,
          description: `${bucket.label} makes up ${percentage.toFixed(1)}% of your total portfolio value (${bucket.value.toFixed(2)}), above the ${REBALANCE_CONCENTRATION_THRESHOLD_PCT}% concentration level generally considered a diversification risk. Consider whether this weighting is intentional.`,
          dataPoint: { dimension: "assetClass", category: bucket.label, percentage, value: bucket.value, threshold: REBALANCE_CONCENTRATION_THRESHOLD_PCT },
          dedupeKey: `rebalance:assetClass:${bucket.label}`,
        });
      }
    }

    // Holding-level concentration — a stricter, lower threshold: any SINGLE
    // stock/crypto position dominating the portfolio is a distinct,
    // well-established risk from category-level concentration above.
    const stockHoldings = await this.prisma.stockHolding.findMany({
      where: { userId, asset: { deletedAt: null } },
      include: { asset: true },
    });
    const totalValue = allocation?.totalValue ?? 0;
    if (totalValue > 0) {
      for (const h of stockHoldings) {
        const value = Number(h.asset.currentValue.toString());
        const pct = (value / totalValue) * 100;
        if (pct >= SELL_SINGLE_HOLDING_THRESHOLD_PCT) {
          out.push({
            type: "SELL",
            title: `${h.ticker} is ${pct.toFixed(0)}% of your net worth`,
            description: `Your ${h.ticker} position is worth ${value.toFixed(2)}, which is ${pct.toFixed(1)}% of your total portfolio value — above the ${SELL_SINGLE_HOLDING_THRESHOLD_PCT}% level where a single holding is generally considered a concentration risk. Consider trimming the position to reduce single-stock exposure.`,
            dataPoint: { ticker: h.ticker, holdingId: h.id, value, percentage: pct, threshold: SELL_SINGLE_HOLDING_THRESHOLD_PCT },
            dedupeKey: `sell-concentration:${h.id}`,
          });
        }
      }
    }

    return out;
  }

  private async checkGoalProbability(userId: string): Promise<DraftSuggestion[]> {
    const goalList = await this.goals.findAll(userId);
    const out: DraftSuggestion[] = [];
    for (const goal of goalList) {
      const probability = await this.goals.getSuccessProbability(userId, goal.id).catch(() => null);
      if (!probability || isSuccessProbabilityError(probability) || probability.alreadyAchieved) continue;
      if (probability.probabilityOfTarget < LOW_SUCCESS_PROBABILITY_THRESHOLD) {
        out.push({
          type: "INCREASE_SIP",
          title: `"${goal.name}" is on track only ${(probability.probabilityOfTarget * 100).toFixed(0)}% of the time`,
          description: `A Monte Carlo simulation of "${goal.name}" (target ${goal.targetAmount} ${goal.currencyCode} by ${new Date(goal.targetDate).toDateString()}) at your current contribution of ${probability.contributionUsed.toFixed(2)}/month succeeds in only ${(probability.probabilityOfTarget * 100).toFixed(0)}% of simulated outcomes. The mathematically required contribution is ${probability.requiredMonthlyContribution.toFixed(2)}/month. Consider increasing your SIP toward that figure.`,
          dataPoint: {
            goalId: goal.id,
            goalName: goal.name,
            probabilityOfTarget: probability.probabilityOfTarget,
            contributionUsed: probability.contributionUsed,
            requiredMonthlyContribution: probability.requiredMonthlyContribution,
            threshold: LOW_SUCCESS_PROBABILITY_THRESHOLD,
          },
          dedupeKey: `increase-sip:${goal.id}`,
        });
      }
    }
    return out;
  }

  private async refineDescription(draft: DraftSuggestion): Promise<string> {
    try {
      const result = await this.orchestrator.complete([
        {
          role: "user",
          content: `Rewrite this financial suggestion in 1-2 clear, friendly sentences for a personal finance app. Do NOT change or invent any number — use exactly the figures given. Original: "${draft.description}"`,
        },
      ]);
      return result.text.trim() || draft.description;
    } catch {
      return draft.description; // rules-generated description is a complete, real fallback — never blocks on the LLM
    }
  }

  async listActive(userId: string) {
    return this.prisma.aiSuggestion.findMany({ where: { userId, status: "ACTIVE" }, orderBy: { createdAt: "desc" } });
  }

  async setStatus(userId: string, id: string, status: "DISMISSED" | "ACTED_ON") {
    return this.prisma.aiSuggestion.updateMany({ where: { id, userId }, data: { status } });
  }
}

function isUniqueConstraintViolation(err: unknown): boolean {
  return typeof err === "object" && err !== null && "code" in err && (err as { code?: unknown }).code === "P2002";
}
